# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security
#aqui te permite loguiar todo tu proyecto que sea seguro.... lo cambias de
#false a true.

all:
  is_secure: false
